const baseAlbum = [
  {
    group: "A",
    items: [
      {
        name: "qatar",
        items: [
          { number: 1, owned: 0, consider: true },
          { number: 2, owned: 0, consider: true },
          { number: 3, owned: 0, consider: true },
          { number: 4, owned: 0, consider: true },
          { number: 5, owned: 0, consider: true },
          { number: 6, owned: 0, consider: true },
          { number: 7, owned: 0, consider: true },
          { number: 8, owned: 0, consider: true },
          { number: 9, owned: 0, consider: true },
          { number: 10, owned: 0, consider: true },
          { number: 11, owned: 0, consider: true },
          { number: 12, owned: 0, consider: true },
          { number: 13, owned: 0, consider: true },
          { number: 14, owned: 0, consider: true },
          { number: 15, owned: 0, consider: true },
          { number: 16, owned: 0, consider: true },
          { number: 17, owned: 0, consider: true },
          { number: 18, owned: 0, consider: true },
          { number: 19, owned: 0, consider: true },
          { number: 20, owned: 0, consider: true },
        ],
      },
      {
        name: "ecuador",
        items: [
          { number: 1, owned: 0, consider: true },
          { number: 2, owned: 0, consider: true },
          { number: 3, owned: 0, consider: true },
          { number: 4, owned: 0, consider: true },
          { number: 5, owned: 0, consider: true },
          { number: 6, owned: 0, consider: true },
          { number: 7, owned: 0, consider: true },
          { number: 8, owned: 0, consider: true },
          { number: 9, owned: 0, consider: true },
          { number: 10, owned: 0, consider: true },
          { number: 11, owned: 0, consider: true },
          { number: 12, owned: 0, consider: true },
          { number: 13, owned: 0, consider: true },
          { number: 14, owned: 0, consider: true },
          { number: 15, owned: 0, consider: true },
          { number: 16, owned: 0, consider: true },
          { number: 17, owned: 0, consider: true },
          { number: 18, owned: 0, consider: true },
          { number: 19, owned: 0, consider: true },
          { number: 20, owned: 0, consider: true },
        ],
      },
      {
        name: "senegal",
        items: [
          { number: 1, owned: 0, consider: true },
          { number: 2, owned: 0, consider: true },
          { number: 3, owned: 0, consider: true },
          { number: 4, owned: 0, consider: true },
          { number: 5, owned: 0, consider: true },
          { number: 6, owned: 0, consider: true },
          { number: 7, owned: 0, consider: true },
          { number: 8, owned: 0, consider: true },
          { number: 9, owned: 0, consider: true },
          { number: 10, owned: 0, consider: true },
          { number: 11, owned: 0, consider: true },
          { number: 12, owned: 0, consider: true },
          { number: 13, owned: 0, consider: true },
          { number: 14, owned: 0, consider: true },
          { number: 15, owned: 0, consider: true },
          { number: 16, owned: 0, consider: true },
          { number: 17, owned: 0, consider: true },
          { number: 18, owned: 0, consider: true },
          { number: 19, owned: 0, consider: true },
          { number: 20, owned: 0, consider: true },
        ],
      },
      {
        name: "netherlands",
        items: [
          { number: 1, owned: 0, consider: true },
          { number: 2, owned: 0, consider: true },
          { number: 3, owned: 0, consider: true },
          { number: 4, owned: 0, consider: true },
          { number: 5, owned: 0, consider: true },
          { number: 6, owned: 0, consider: true },
          { number: 7, owned: 0, consider: true },
          { number: 8, owned: 0, consider: true },
          { number: 9, owned: 0, consider: true },
          { number: 10, owned: 0, consider: true },
          { number: 11, owned: 0, consider: true },
          { number: 12, owned: 0, consider: true },
          { number: 13, owned: 0, consider: true },
          { number: 14, owned: 0, consider: true },
          { number: 15, owned: 0, consider: true },
          { number: 16, owned: 0, consider: true },
          { number: 17, owned: 0, consider: true },
          { number: 18, owned: 0, consider: true },
          { number: 19, owned: 0, consider: true },
          { number: 20, owned: 0, consider: true },
        ],
      },
    ],
  },
  {
    group: "B",

    items: [
      {
        name: "england",
        items: [
          { number: 1, owned: 0, consider: true },
          { number: 2, owned: 0, consider: true },
          { number: 3, owned: 0, consider: true },
          { number: 4, owned: 0, consider: true },
          { number: 5, owned: 0, consider: true },
          { number: 6, owned: 0, consider: true },
          { number: 7, owned: 0, consider: true },
          { number: 8, owned: 0, consider: true },
          { number: 9, owned: 0, consider: true },
          { number: 10, owned: 0, consider: true },
          { number: 11, owned: 0, consider: true },
          { number: 12, owned: 0, consider: true },
          { number: 13, owned: 0, consider: true },
          { number: 14, owned: 0, consider: true },
          { number: 15, owned: 0, consider: true },
          { number: 16, owned: 0, consider: true },
          { number: 17, owned: 0, consider: true },
          { number: 18, owned: 0, consider: true },
          { number: 19, owned: 0, consider: true },
          { number: 20, owned: 0, consider: true },
        ],
      },
      {
        name: "iran",
        items: [
          { number: 1, owned: 0, consider: true },
          { number: 2, owned: 0, consider: true },
          { number: 3, owned: 0, consider: true },
          { number: 4, owned: 0, consider: true },
          { number: 5, owned: 0, consider: true },
          { number: 6, owned: 0, consider: true },
          { number: 7, owned: 0, consider: true },
          { number: 8, owned: 0, consider: true },
          { number: 9, owned: 0, consider: true },
          { number: 10, owned: 0, consider: true },
          { number: 11, owned: 0, consider: true },
          { number: 12, owned: 0, consider: true },
          { number: 13, owned: 0, consider: true },
          { number: 14, owned: 0, consider: true },
          { number: 15, owned: 0, consider: true },
          { number: 16, owned: 0, consider: true },
          { number: 17, owned: 0, consider: true },
          { number: 18, owned: 0, consider: true },
          { number: 19, owned: 0, consider: true },
          { number: 20, owned: 0, consider: true },
        ],
      },
      {
        name: "unitedstates",
        items: [
          { number: 1, owned: 0, consider: true },
          { number: 2, owned: 0, consider: true },
          { number: 3, owned: 0, consider: true },
          { number: 4, owned: 0, consider: true },
          { number: 5, owned: 0, consider: true },
          { number: 6, owned: 0, consider: true },
          { number: 7, owned: 0, consider: true },
          { number: 8, owned: 0, consider: true },
          { number: 9, owned: 0, consider: true },
          { number: 10, owned: 0, consider: true },
          { number: 11, owned: 0, consider: true },
          { number: 12, owned: 0, consider: true },
          { number: 13, owned: 0, consider: true },
          { number: 14, owned: 0, consider: true },
          { number: 15, owned: 0, consider: true },
          { number: 16, owned: 0, consider: true },
          { number: 17, owned: 0, consider: true },
          { number: 18, owned: 0, consider: true },
          { number: 19, owned: 0, consider: true },
          { number: 20, owned: 0, consider: true },
        ],
      },
      {
        name: "wales",
        items: [
          { number: 1, owned: 0, consider: true },
          { number: 2, owned: 0, consider: true },
          { number: 3, owned: 0, consider: true },
          { number: 4, owned: 0, consider: true },
          { number: 5, owned: 0, consider: true },
          { number: 6, owned: 0, consider: true },
          { number: 7, owned: 0, consider: true },
          { number: 8, owned: 0, consider: true },
          { number: 9, owned: 0, consider: true },
          { number: 10, owned: 0, consider: true },
          { number: 11, owned: 0, consider: true },
          { number: 12, owned: 0, consider: true },
          { number: 13, owned: 0, consider: true },
          { number: 14, owned: 0, consider: true },
          { number: 15, owned: 0, consider: true },
          { number: 16, owned: 0, consider: true },
          { number: 17, owned: 0, consider: true },
          { number: 18, owned: 0, consider: true },
          { number: 19, owned: 0, consider: true },
          { number: 20, owned: 0, consider: true },
        ],
      },
    ],
  },
  {
    group: "C",
    items: [
      {
        name: "argentina",
        items: [
          { number: 1, owned: 0, consider: true },
          { number: 2, owned: 0, consider: true },
          { number: 3, owned: 0, consider: true },
          { number: 4, owned: 0, consider: true },
          { number: 5, owned: 0, consider: true },
          { number: 6, owned: 0, consider: true },
          { number: 7, owned: 0, consider: true },
          { number: 8, owned: 0, consider: true },
          { number: 9, owned: 0, consider: true },
          { number: 10, owned: 0, consider: true },
          { number: 11, owned: 0, consider: true },
          { number: 12, owned: 0, consider: true },
          { number: 13, owned: 0, consider: true },
          { number: 14, owned: 0, consider: true },
          { number: 15, owned: 0, consider: true },
          { number: 16, owned: 0, consider: true },
          { number: 17, owned: 0, consider: true },
          { number: 18, owned: 0, consider: true },
          { number: 19, owned: 0, consider: true },
          { number: 20, owned: 0, consider: true },
        ],
      },
      {
        name: "saudiarabia",
        items: [
          { number: 1, owned: 0, consider: true },
          { number: 2, owned: 0, consider: true },
          { number: 3, owned: 0, consider: true },
          { number: 4, owned: 0, consider: true },
          { number: 5, owned: 0, consider: true },
          { number: 6, owned: 0, consider: true },
          { number: 7, owned: 0, consider: true },
          { number: 8, owned: 0, consider: true },
          { number: 9, owned: 0, consider: true },
          { number: 10, owned: 0, consider: true },
          { number: 11, owned: 0, consider: true },
          { number: 12, owned: 0, consider: true },
          { number: 13, owned: 0, consider: true },
          { number: 14, owned: 0, consider: true },
          { number: 15, owned: 0, consider: true },
          { number: 16, owned: 0, consider: true },
          { number: 17, owned: 0, consider: true },
          { number: 18, owned: 0, consider: true },
          { number: 19, owned: 0, consider: true },
          { number: 20, owned: 0, consider: true },
        ],
      },
      {
        name: "mexico",
        items: [
          { number: 1, owned: 0, consider: true },
          { number: 2, owned: 0, consider: true },
          { number: 3, owned: 0, consider: true },
          { number: 4, owned: 0, consider: true },
          { number: 5, owned: 0, consider: true },
          { number: 6, owned: 0, consider: true },
          { number: 7, owned: 0, consider: true },
          { number: 8, owned: 0, consider: true },
          { number: 9, owned: 0, consider: true },
          { number: 10, owned: 0, consider: true },
          { number: 11, owned: 0, consider: true },
          { number: 12, owned: 0, consider: true },
          { number: 13, owned: 0, consider: true },
          { number: 14, owned: 0, consider: true },
          { number: 15, owned: 0, consider: true },
          { number: 16, owned: 0, consider: true },
          { number: 17, owned: 0, consider: true },
          { number: 18, owned: 0, consider: true },
          { number: 19, owned: 0, consider: true },
          { number: 20, owned: 0, consider: true },
        ],
      },
      {
        name: "poland",
        items: [
          { number: 1, owned: 0, consider: true },
          { number: 2, owned: 0, consider: true },
          { number: 3, owned: 0, consider: true },
          { number: 4, owned: 0, consider: true },
          { number: 5, owned: 0, consider: true },
          { number: 6, owned: 0, consider: true },
          { number: 7, owned: 0, consider: true },
          { number: 8, owned: 0, consider: true },
          { number: 9, owned: 0, consider: true },
          { number: 10, owned: 0, consider: true },
          { number: 11, owned: 0, consider: true },
          { number: 12, owned: 0, consider: true },
          { number: 13, owned: 0, consider: true },
          { number: 14, owned: 0, consider: true },
          { number: 15, owned: 0, consider: true },
          { number: 16, owned: 0, consider: true },
          { number: 17, owned: 0, consider: true },
          { number: 18, owned: 0, consider: true },
          { number: 19, owned: 0, consider: true },
          { number: 20, owned: 0, consider: true },
        ],
      },
    ],
  },
  {
    group: "D",

    items: [
      {
        name: "france",
        items: [
          { number: 1, owned: 0, consider: true },
          { number: 2, owned: 0, consider: true },
          { number: 3, owned: 0, consider: true },
          { number: 4, owned: 0, consider: true },
          { number: 5, owned: 0, consider: true },
          { number: 6, owned: 0, consider: true },
          { number: 7, owned: 0, consider: true },
          { number: 8, owned: 0, consider: true },
          { number: 9, owned: 0, consider: true },
          { number: 10, owned: 0, consider: true },
          { number: 11, owned: 0, consider: true },
          { number: 12, owned: 0, consider: true },
          { number: 13, owned: 0, consider: true },
          { number: 14, owned: 0, consider: true },
          { number: 15, owned: 0, consider: true },
          { number: 16, owned: 0, consider: true },
          { number: 17, owned: 0, consider: true },
          { number: 18, owned: 0, consider: true },
          { number: 19, owned: 0, consider: true },
          { number: 20, owned: 0, consider: true },
        ],
      },
      {
        name: "australia",
        items: [
          { number: 1, owned: 0, consider: true },
          { number: 2, owned: 0, consider: true },
          { number: 3, owned: 0, consider: true },
          { number: 4, owned: 0, consider: true },
          { number: 5, owned: 0, consider: true },
          { number: 6, owned: 0, consider: true },
          { number: 7, owned: 0, consider: true },
          { number: 8, owned: 0, consider: true },
          { number: 9, owned: 0, consider: true },
          { number: 10, owned: 0, consider: true },
          { number: 11, owned: 0, consider: true },
          { number: 12, owned: 0, consider: true },
          { number: 13, owned: 0, consider: true },
          { number: 14, owned: 0, consider: true },
          { number: 15, owned: 0, consider: true },
          { number: 16, owned: 0, consider: true },
          { number: 17, owned: 0, consider: true },
          { number: 18, owned: 0, consider: true },
          { number: 19, owned: 0, consider: true },
          { number: 20, owned: 0, consider: true },
        ],
      },
      {
        name: "denmark",
        items: [
          { number: 1, owned: 0, consider: true },
          { number: 2, owned: 0, consider: true },
          { number: 3, owned: 0, consider: true },
          { number: 4, owned: 0, consider: true },
          { number: 5, owned: 0, consider: true },
          { number: 6, owned: 0, consider: true },
          { number: 7, owned: 0, consider: true },
          { number: 8, owned: 0, consider: true },
          { number: 9, owned: 0, consider: true },
          { number: 10, owned: 0, consider: true },
          { number: 11, owned: 0, consider: true },
          { number: 12, owned: 0, consider: true },
          { number: 13, owned: 0, consider: true },
          { number: 14, owned: 0, consider: true },
          { number: 15, owned: 0, consider: true },
          { number: 16, owned: 0, consider: true },
          { number: 17, owned: 0, consider: true },
          { number: 18, owned: 0, consider: true },
          { number: 19, owned: 0, consider: true },
          { number: 20, owned: 0, consider: true },
        ],
      },
      {
        name: "tunisia",
        items: [
          { number: 1, owned: 0, consider: true },
          { number: 2, owned: 0, consider: true },
          { number: 3, owned: 0, consider: true },
          { number: 4, owned: 0, consider: true },
          { number: 5, owned: 0, consider: true },
          { number: 6, owned: 0, consider: true },
          { number: 7, owned: 0, consider: true },
          { number: 8, owned: 0, consider: true },
          { number: 9, owned: 0, consider: true },
          { number: 10, owned: 0, consider: true },
          { number: 11, owned: 0, consider: true },
          { number: 12, owned: 0, consider: true },
          { number: 13, owned: 0, consider: true },
          { number: 14, owned: 0, consider: true },
          { number: 15, owned: 0, consider: true },
          { number: 16, owned: 0, consider: true },
          { number: 17, owned: 0, consider: true },
          { number: 18, owned: 0, consider: true },
          { number: 19, owned: 0, consider: true },
          { number: 20, owned: 0, consider: true },
        ],
      },
    ],
  },
  {
    group: "E",
    items: [
      {
        name: "spain",
        items: [
          { number: 1, owned: 0, consider: true },
          { number: 2, owned: 0, consider: true },
          { number: 3, owned: 0, consider: true },
          { number: 4, owned: 0, consider: true },
          { number: 5, owned: 0, consider: true },
          { number: 6, owned: 0, consider: true },
          { number: 7, owned: 0, consider: true },
          { number: 8, owned: 0, consider: true },
          { number: 9, owned: 0, consider: true },
          { number: 10, owned: 0, consider: true },
          { number: 11, owned: 0, consider: true },
          { number: 12, owned: 0, consider: true },
          { number: 13, owned: 0, consider: true },
          { number: 14, owned: 0, consider: true },
          { number: 15, owned: 0, consider: true },
          { number: 16, owned: 0, consider: true },
          { number: 17, owned: 0, consider: true },
          { number: 18, owned: 0, consider: true },
          { number: 19, owned: 0, consider: true },
          { number: 20, owned: 0, consider: true },
        ],
      },
      {
        name: "costarica",
        items: [
          { number: 1, owned: 0, consider: true },
          { number: 2, owned: 0, consider: true },
          { number: 3, owned: 0, consider: true },
          { number: 4, owned: 0, consider: true },
          { number: 5, owned: 0, consider: true },
          { number: 6, owned: 0, consider: true },
          { number: 7, owned: 0, consider: true },
          { number: 8, owned: 0, consider: true },
          { number: 9, owned: 0, consider: true },
          { number: 10, owned: 0, consider: true },
          { number: 11, owned: 0, consider: true },
          { number: 12, owned: 0, consider: true },
          { number: 13, owned: 0, consider: true },
          { number: 14, owned: 0, consider: true },
          { number: 15, owned: 0, consider: true },
          { number: 16, owned: 0, consider: true },
          { number: 17, owned: 0, consider: true },
          { number: 18, owned: 0, consider: true },
          { number: 19, owned: 0, consider: true },
          { number: 20, owned: 0, consider: true },
        ],
      },
      {
        name: "germany",
        items: [
          { number: 1, owned: 0, consider: true },
          { number: 2, owned: 0, consider: true },
          { number: 3, owned: 0, consider: true },
          { number: 4, owned: 0, consider: true },
          { number: 5, owned: 0, consider: true },
          { number: 6, owned: 0, consider: true },
          { number: 7, owned: 0, consider: true },
          { number: 8, owned: 0, consider: true },
          { number: 9, owned: 0, consider: true },
          { number: 10, owned: 0, consider: true },
          { number: 11, owned: 0, consider: true },
          { number: 12, owned: 0, consider: true },
          { number: 13, owned: 0, consider: true },
          { number: 14, owned: 0, consider: true },
          { number: 15, owned: 0, consider: true },
          { number: 16, owned: 0, consider: true },
          { number: 17, owned: 0, consider: true },
          { number: 18, owned: 0, consider: true },
          { number: 19, owned: 0, consider: true },
          { number: 20, owned: 0, consider: true },
        ],
      },
      {
        name: "japan",
        items: [
          { number: 1, owned: 0, consider: true },
          { number: 2, owned: 0, consider: true },
          { number: 3, owned: 0, consider: true },
          { number: 4, owned: 0, consider: true },
          { number: 5, owned: 0, consider: true },
          { number: 6, owned: 0, consider: true },
          { number: 7, owned: 0, consider: true },
          { number: 8, owned: 0, consider: true },
          { number: 9, owned: 0, consider: true },
          { number: 10, owned: 0, consider: true },
          { number: 11, owned: 0, consider: true },
          { number: 12, owned: 0, consider: true },
          { number: 13, owned: 0, consider: true },
          { number: 14, owned: 0, consider: true },
          { number: 15, owned: 0, consider: true },
          { number: 16, owned: 0, consider: true },
          { number: 17, owned: 0, consider: true },
          { number: 18, owned: 0, consider: true },
          { number: 19, owned: 0, consider: true },
          { number: 20, owned: 0, consider: true },
        ],
      },
    ],
  },
  {
    group: "F",
    items: [
      {
        name: "belgium",
        items: [
          { number: 1, owned: 0, consider: true },
          { number: 2, owned: 0, consider: true },
          { number: 3, owned: 0, consider: true },
          { number: 4, owned: 0, consider: true },
          { number: 5, owned: 0, consider: true },
          { number: 6, owned: 0, consider: true },
          { number: 7, owned: 0, consider: true },
          { number: 8, owned: 0, consider: true },
          { number: 9, owned: 0, consider: true },
          { number: 10, owned: 0, consider: true },
          { number: 11, owned: 0, consider: true },
          { number: 12, owned: 0, consider: true },
          { number: 13, owned: 0, consider: true },
          { number: 14, owned: 0, consider: true },
          { number: 15, owned: 0, consider: true },
          { number: 16, owned: 0, consider: true },
          { number: 17, owned: 0, consider: true },
          { number: 18, owned: 0, consider: true },
          { number: 19, owned: 0, consider: true },
          { number: 20, owned: 0, consider: true },
        ],
      },
      {
        name: "canada",
        items: [
          { number: 1, owned: 0, consider: true },
          { number: 2, owned: 0, consider: true },
          { number: 3, owned: 0, consider: true },
          { number: 4, owned: 0, consider: true },
          { number: 5, owned: 0, consider: true },
          { number: 6, owned: 0, consider: true },
          { number: 7, owned: 0, consider: true },
          { number: 8, owned: 0, consider: true },
          { number: 9, owned: 0, consider: true },
          { number: 10, owned: 0, consider: true },
          { number: 11, owned: 0, consider: true },
          { number: 12, owned: 0, consider: true },
          { number: 13, owned: 0, consider: true },
          { number: 14, owned: 0, consider: true },
          { number: 15, owned: 0, consider: true },
          { number: 16, owned: 0, consider: true },
          { number: 17, owned: 0, consider: true },
          { number: 18, owned: 0, consider: true },
          { number: 19, owned: 0, consider: true },
          { number: 20, owned: 0, consider: true },
        ],
      },
      {
        name: "morocco",
        items: [
          { number: 1, owned: 0, consider: true },
          { number: 2, owned: 0, consider: true },
          { number: 3, owned: 0, consider: true },
          { number: 4, owned: 0, consider: true },
          { number: 5, owned: 0, consider: true },
          { number: 6, owned: 0, consider: true },
          { number: 7, owned: 0, consider: true },
          { number: 8, owned: 0, consider: true },
          { number: 9, owned: 0, consider: true },
          { number: 10, owned: 0, consider: true },
          { number: 11, owned: 0, consider: true },
          { number: 12, owned: 0, consider: true },
          { number: 13, owned: 0, consider: true },
          { number: 14, owned: 0, consider: true },
          { number: 15, owned: 0, consider: true },
          { number: 16, owned: 0, consider: true },
          { number: 17, owned: 0, consider: true },
          { number: 18, owned: 0, consider: true },
          { number: 19, owned: 0, consider: true },
          { number: 20, owned: 0, consider: true },
        ],
      },
      {
        name: "croatia",
        items: [
          { number: 1, owned: 0, consider: true },
          { number: 2, owned: 0, consider: true },
          { number: 3, owned: 0, consider: true },
          { number: 4, owned: 0, consider: true },
          { number: 5, owned: 0, consider: true },
          { number: 6, owned: 0, consider: true },
          { number: 7, owned: 0, consider: true },
          { number: 8, owned: 0, consider: true },
          { number: 9, owned: 0, consider: true },
          { number: 10, owned: 0, consider: true },
          { number: 11, owned: 0, consider: true },
          { number: 12, owned: 0, consider: true },
          { number: 13, owned: 0, consider: true },
          { number: 14, owned: 0, consider: true },
          { number: 15, owned: 0, consider: true },
          { number: 16, owned: 0, consider: true },
          { number: 17, owned: 0, consider: true },
          { number: 18, owned: 0, consider: true },
          { number: 19, owned: 0, consider: true },
          { number: 20, owned: 0, consider: true },
        ],
      },
    ],
  },
  {
    group: "G",
    items: [
      {
        name: "brazil",
        items: [
          { number: 1, owned: 0, consider: true },
          { number: 2, owned: 0, consider: true },
          { number: 3, owned: 0, consider: true },
          { number: 4, owned: 0, consider: true },
          { number: 5, owned: 0, consider: true },
          { number: 6, owned: 0, consider: true },
          { number: 7, owned: 0, consider: true },
          { number: 8, owned: 0, consider: true },
          { number: 9, owned: 0, consider: true },
          { number: 10, owned: 0, consider: true },
          { number: 11, owned: 0, consider: true },
          { number: 12, owned: 0, consider: true },
          { number: 13, owned: 0, consider: true },
          { number: 14, owned: 0, consider: true },
          { number: 15, owned: 0, consider: true },
          { number: 16, owned: 0, consider: true },
          { number: 17, owned: 0, consider: true },
          { number: 18, owned: 0, consider: true },
          { number: 19, owned: 0, consider: true },
          { number: 20, owned: 0, consider: true },
        ],
      },
      {
        name: "serbia",
        items: [
          { number: 1, owned: 0, consider: true },
          { number: 2, owned: 0, consider: true },
          { number: 3, owned: 0, consider: true },
          { number: 4, owned: 0, consider: true },
          { number: 5, owned: 0, consider: true },
          { number: 6, owned: 0, consider: true },
          { number: 7, owned: 0, consider: true },
          { number: 8, owned: 0, consider: true },
          { number: 9, owned: 0, consider: true },
          { number: 10, owned: 0, consider: true },
          { number: 11, owned: 0, consider: true },
          { number: 12, owned: 0, consider: true },
          { number: 13, owned: 0, consider: true },
          { number: 14, owned: 0, consider: true },
          { number: 15, owned: 0, consider: true },
          { number: 16, owned: 0, consider: true },
          { number: 17, owned: 0, consider: true },
          { number: 18, owned: 0, consider: true },
          { number: 19, owned: 0, consider: true },
          { number: 20, owned: 0, consider: true },
        ],
      },
      {
        name: "switzerland",
        items: [
          { number: 1, owned: 0, consider: true },
          { number: 2, owned: 0, consider: true },
          { number: 3, owned: 0, consider: true },
          { number: 4, owned: 0, consider: true },
          { number: 5, owned: 0, consider: true },
          { number: 6, owned: 0, consider: true },
          { number: 7, owned: 0, consider: true },
          { number: 8, owned: 0, consider: true },
          { number: 9, owned: 0, consider: true },
          { number: 10, owned: 0, consider: true },
          { number: 11, owned: 0, consider: true },
          { number: 12, owned: 0, consider: true },
          { number: 13, owned: 0, consider: true },
          { number: 14, owned: 0, consider: true },
          { number: 15, owned: 0, consider: true },
          { number: 16, owned: 0, consider: true },
          { number: 17, owned: 0, consider: true },
          { number: 18, owned: 0, consider: true },
          { number: 19, owned: 0, consider: true },
          { number: 20, owned: 0, consider: true },
        ],
      },
      {
        name: "cameroon",
        items: [
          { number: 1, owned: 0, consider: true },
          { number: 2, owned: 0, consider: true },
          { number: 3, owned: 0, consider: true },
          { number: 4, owned: 0, consider: true },
          { number: 5, owned: 0, consider: true },
          { number: 6, owned: 0, consider: true },
          { number: 7, owned: 0, consider: true },
          { number: 8, owned: 0, consider: true },
          { number: 9, owned: 0, consider: true },
          { number: 10, owned: 0, consider: true },
          { number: 11, owned: 0, consider: true },
          { number: 12, owned: 0, consider: true },
          { number: 13, owned: 0, consider: true },
          { number: 14, owned: 0, consider: true },
          { number: 15, owned: 0, consider: true },
          { number: 16, owned: 0, consider: true },
          { number: 17, owned: 0, consider: true },
          { number: 18, owned: 0, consider: true },
          { number: 19, owned: 0, consider: true },
          { number: 20, owned: 0, consider: true },
        ],
      },
    ],
  },
  {
    group: "H",
    items: [
      {
        name: "portugal",
        items: [
          { number: 1, owned: 0, consider: true },
          { number: 2, owned: 0, consider: true },
          { number: 3, owned: 0, consider: true },
          { number: 4, owned: 0, consider: true },
          { number: 5, owned: 0, consider: true },
          { number: 6, owned: 0, consider: true },
          { number: 7, owned: 0, consider: true },
          { number: 8, owned: 0, consider: true },
          { number: 9, owned: 0, consider: true },
          { number: 10, owned: 0, consider: true },
          { number: 11, owned: 0, consider: true },
          { number: 12, owned: 0, consider: true },
          { number: 13, owned: 0, consider: true },
          { number: 14, owned: 0, consider: true },
          { number: 15, owned: 0, consider: true },
          { number: 16, owned: 0, consider: true },
          { number: 17, owned: 0, consider: true },
          { number: 18, owned: 0, consider: true },
          { number: 19, owned: 0, consider: true },
          { number: 20, owned: 0, consider: true },
        ],
      },
      {
        name: "ghana",
        items: [
          { number: 1, owned: 0, consider: true },
          { number: 2, owned: 0, consider: true },
          { number: 3, owned: 0, consider: true },
          { number: 4, owned: 0, consider: true },
          { number: 5, owned: 0, consider: true },
          { number: 6, owned: 0, consider: true },
          { number: 7, owned: 0, consider: true },
          { number: 8, owned: 0, consider: true },
          { number: 9, owned: 0, consider: true },
          { number: 10, owned: 0, consider: true },
          { number: 11, owned: 0, consider: true },
          { number: 12, owned: 0, consider: true },
          { number: 13, owned: 0, consider: true },
          { number: 14, owned: 0, consider: true },
          { number: 15, owned: 0, consider: true },
          { number: 16, owned: 0, consider: true },
          { number: 17, owned: 0, consider: true },
          { number: 18, owned: 0, consider: true },
          { number: 19, owned: 0, consider: true },
          { number: 20, owned: 0, consider: true },
        ],
      },
      {
        name: "uruguay",
        items: [
          { number: 1, owned: 0, consider: true },
          { number: 2, owned: 0, consider: true },
          { number: 3, owned: 0, consider: true },
          { number: 4, owned: 0, consider: true },
          { number: 5, owned: 0, consider: true },
          { number: 6, owned: 0, consider: true },
          { number: 7, owned: 0, consider: true },
          { number: 8, owned: 0, consider: true },
          { number: 9, owned: 0, consider: true },
          { number: 10, owned: 0, consider: true },
          { number: 11, owned: 0, consider: true },
          { number: 12, owned: 0, consider: true },
          { number: 13, owned: 0, consider: true },
          { number: 14, owned: 0, consider: true },
          { number: 15, owned: 0, consider: true },
          { number: 16, owned: 0, consider: true },
          { number: 17, owned: 0, consider: true },
          { number: 18, owned: 0, consider: true },
          { number: 19, owned: 0, consider: true },
          { number: 20, owned: 0, consider: true },
        ],
      },
      {
        name: "southkorea",
        items: [
          { number: 1, owned: 0, consider: true },
          { number: 2, owned: 0, consider: true },
          { number: 3, owned: 0, consider: true },
          { number: 4, owned: 0, consider: true },
          { number: 5, owned: 0, consider: true },
          { number: 6, owned: 0, consider: true },
          { number: 7, owned: 0, consider: true },
          { number: 8, owned: 0, consider: true },
          { number: 9, owned: 0, consider: true },
          { number: 10, owned: 0, consider: true },
          { number: 11, owned: 0, consider: true },
          { number: 12, owned: 0, consider: true },
          { number: 13, owned: 0, consider: true },
          { number: 14, owned: 0, consider: true },
          { number: 15, owned: 0, consider: true },
          { number: 16, owned: 0, consider: true },
          { number: 17, owned: 0, consider: true },
          { number: 18, owned: 0, consider: true },
          { number: 19, owned: 0, consider: true },
          { number: 20, owned: 0, consider: true },
        ],
      },
    ],
  },
  {
    group: "officialtrofy",
    FWC1: { number: 0, consider: true },
    FWC2: { number: 0, consider: true },
    FWC3: { number: 0, consider: true },
    FWC4: { number: 0, consider: true },
    FWC5: { number: 0, consider: true },
    FWC6: { number: 0, consider: true },
    FWC7: { number: 0, consider: true },
    FWC8: { number: 0, consider: true },
    FWC9: { number: 0, consider: true },
    FWC10: { number: 0, consider: true },
    FWC11: { number: 0, consider: true },
    FWC12: { number: 0, consider: true },
    FWC13: { number: 0, consider: true },
    FWC14: { number: 0, consider: true },
    FWC15: { number: 0, consider: true },
    FWC16: { number: 0, consider: true },
    FWC17: { number: 0, consider: true },
    FWC18: { number: 0, consider: true },
  },
  {
    group: "museum",
    FWC19: { number: 0, consider: true },
    FWC20: { number: 0, consider: true },
    FWC21: { number: 0, consider: true },
    FWC22: { number: 0, consider: true },
    FWC23: { number: 0, consider: true },
    FWC24: { number: 0, consider: true },
    FWC25: { number: 0, consider: true },
    FWC26: { number: 0, consider: true },
    FWC27: { number: 0, consider: true },
    FWC28: { number: 0, consider: true },
    FWC29: { number: 0, consider: true },
  },
];

export default baseAlbum;
