import "primevue/resources/themes/saga-blue/theme.css"; //theme
import "primevue/resources/primevue.min.css"; //core css
import "primeicons/primeicons.css"; //icons

import PrimeVue from "primevue/config";
import AutoComplete from "primevue/autocomplete";
import Accordion from "primevue/accordion";
import AccordionTab from "primevue/accordiontab";
import Avatar from "primevue/avatar";
import AvatarGroup from "primevue/avatargroup";
import Badge from "primevue/badge";
import BadgeDirective from "primevue/badgedirective";
import Button from "primevue/button";
import Breadcrumb from "primevue/breadcrumb";
import Calendar from "primevue/calendar";
import Card from "primevue/card";
import Carousel from "primevue/carousel";
import Chart from "primevue/chart";
import Checkbox from "primevue/checkbox";
import Chip from "primevue/chip";
import Chips from "primevue/chips";
import ColorPicker from "primevue/colorpicker";
import Column from "primevue/column";
import ConfirmDialog from "primevue/confirmdialog";
import ConfirmPopup from "primevue/confirmpopup";
import ConfirmationService from "primevue/confirmationservice";
import ContextMenu from "primevue/contextmenu";
import DataTable from "primevue/datatable";
import DataView from "primevue/dataview";
import DataViewLayoutOptions from "primevue/dataviewlayoutoptions";
import Dialog from "primevue/dialog";
import Divider from "primevue/divider";
import Dropdown from "primevue/dropdown";
import Fieldset from "primevue/fieldset";
import FileUpload from "primevue/fileupload";
import Image from "primevue/image";
import InlineMessage from "primevue/inlinemessage";
import Inplace from "primevue/inplace";
import InputMask from "primevue/inputmask";
import InputNumber from "primevue/inputnumber";
import InputSwitch from "primevue/inputswitch";
import InputText from "primevue/inputtext";
import Knob from "primevue/knob";
import Galleria from "primevue/galleria";
import Listbox from "primevue/listbox";
import MegaMenu from "primevue/megamenu";
import Menu from "primevue/menu";
import Menubar from "primevue/menubar";
import Message from "primevue/message";
import MultiSelect from "primevue/multiselect";
import OrderList from "primevue/orderlist";
import OrganizationChart from "primevue/organizationchart";
import OverlayPanel from "primevue/overlaypanel";
import Paginator from "primevue/paginator";
import Panel from "primevue/panel";
import PanelMenu from "primevue/panelmenu";
import Password from "primevue/password";
import PickList from "primevue/picklist";
import ProgressBar from "primevue/progressbar";
import Rating from "primevue/rating";
import RadioButton from "primevue/radiobutton";
import Ripple from "primevue/ripple";
import SelectButton from "primevue/selectbutton";
import ScrollPanel from "primevue/scrollpanel";
import ScrollTop from "primevue/scrolltop";
import Slider from "primevue/slider";
import Sidebar from "primevue/sidebar";
import Skeleton from "primevue/skeleton";
import SplitButton from "primevue/splitbutton";
import Splitter from "primevue/splitter";
import SplitterPanel from "primevue/splitterpanel";
import Steps from "primevue/steps";
import StyleClass from "primevue/styleclass";
import TabMenu from "primevue/tabmenu";
import Tag from "primevue/tag";
import TieredMenu from "primevue/tieredmenu";
import Textarea from "primevue/textarea";
import Timeline from "primevue/timeline";
import Toast from "primevue/toast";
import ToastService from "primevue/toastservice";
import Toolbar from "primevue/toolbar";
import TabView from "primevue/tabview";
import TabPanel from "primevue/tabpanel";
import Tooltip from "primevue/tooltip";
import ToggleButton from "primevue/togglebutton";
import Tree from "primevue/tree";
import TreeSelect from "primevue/treeselect";
import TreeTable from "primevue/treetable";
import TriStateCheckbox from "primevue/tristatecheckbox";

class PrimeVueConfigurator {
  constructor() {}

  init(app) {
    app.use(PrimeVue, { ripple: true, inputStyle: "outlined" });
    app.use(ConfirmationService);
    app.use(ToastService);

    app.directive("tooltip", Tooltip);
    app.directive("ripple", Ripple);
    app.directive("badge", BadgeDirective);
    app.directive("styleclass", StyleClass);

    app.component("PVAccordion", Accordion);
    app.component("PVAccordionTab", AccordionTab);
    app.component("PVAutoComplete", AutoComplete);
    app.component("PVAvatar", Avatar);
    app.component("PVAvatarGroup", AvatarGroup);
    app.component("PVBadge", Badge);
    app.component("PVBreadcrumb", Breadcrumb);
    app.component("PVButton", Button);
    app.component("PVCalendar", Calendar);
    app.component("PVCard", Card);
    app.component("PVCarousel", Carousel);
    app.component("PVChart", Chart);
    app.component("PVCheckbox", Checkbox);
    app.component("PVChip", Chip);
    app.component("PVChips", Chips);
    app.component("PVColorPicker", ColorPicker);
    app.component("PVColumn", Column);
    app.component("PVConfirmDialog", ConfirmDialog);
    app.component("PVConfirmPopup", ConfirmPopup);
    app.component("PVContextMenu", ContextMenu);
    app.component("PVDataTable", DataTable);
    app.component("PVDataView", DataView);
    app.component("PVDataViewLayoutOptions", DataViewLayoutOptions);
    app.component("PVDialog", Dialog);
    app.component("PVDivider", Divider);
    app.component("PVDropdown", Dropdown);
    app.component("PVFieldset", Fieldset);
    app.component("PVFileUpload", FileUpload);
    app.component("PVImage", Image);
    app.component("PVInlineMessage", InlineMessage);
    app.component("PVInplace", Inplace);
    app.component("PVInputMask", InputMask);
    app.component("PVInputNumber", InputNumber);
    app.component("PVInputSwitch", InputSwitch);
    app.component("PVInputText", InputText);
    app.component("PVGalleria", Galleria);
    app.component("PVKnob", Knob);
    app.component("PVListbox", Listbox);
    app.component("PVMegaMenu", MegaMenu);
    app.component("PVMenu", Menu);
    app.component("PVMenubar", Menubar);
    app.component("PVMessage", Message);
    app.component("PVMultiSelect", MultiSelect);
    app.component("PVOrderList", OrderList);
    app.component("PVOrganizationChart", OrganizationChart);
    app.component("PVOverlayPanel", OverlayPanel);
    app.component("PVPaginator", Paginator);
    app.component("PVPanel", Panel);
    app.component("PVPanelMenu", PanelMenu);
    app.component("PVPassword", Password);
    app.component("PVPickList", PickList);
    app.component("PVProgressBar", ProgressBar);
    app.component("PVRadioButton", RadioButton);
    app.component("PVRating", Rating);
    app.component("PVSelectButton", SelectButton);
    app.component("PVScrollPanel", ScrollPanel);
    app.component("PVScrollTop", ScrollTop);
    app.component("PVSlider", Slider);
    app.component("PVSidebar", Sidebar);
    app.component("PVSkeleton", Skeleton);
    app.component("PVSplitButton", SplitButton);
    app.component("PVSplitter", Splitter);
    app.component("PVSplitterPanel", SplitterPanel);
    app.component("PVSteps", Steps);
    app.component("PVTabMenu", TabMenu);
    app.component("PVTabView", TabView);
    app.component("PVTabPanel", TabPanel);
    app.component("PVTag", Tag);
    app.component("PVTextarea", Textarea);
    app.component("PVTieredMenu", TieredMenu);
    app.component("PVTimeline", Timeline);
    app.component("PVToast", Toast);
    app.component("PVToolbar", Toolbar);
    app.component("PVToggleButton", ToggleButton);
    app.component("PVTree", Tree);
    app.component("PVTreeSelect", TreeSelect);
    app.component("PVTreeTable", TreeTable);
    app.component("PVTriStateCheckbox", TriStateCheckbox);
  }
}

export default new PrimeVueConfigurator();
